# Generated by Django 6.1 on 2026-08-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Samarth', max_length=100)),
                ('role', models.CharField(default='Full-Stack Web Developer', max_length=200)),
                ('hero_tagline', models.TextField(default='I build fast, reliable, and thoughtfully designed web applications — from database to pixel.')),
                ('about_text_1', models.TextField(blank=True)),
                ('about_text_2', models.TextField(blank=True)),
                ('about_text_3', models.TextField(blank=True)),
                ('years_experience', models.CharField(default='3+', max_length=20)),
                ('projects_shipped', models.CharField(default='25+', max_length=20)),
                ('email', models.EmailField(default='samarth.dev@example.com', max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fullstack', 'Full-Stack'), ('frontend', 'Frontend'), ('api', 'API')], default='fullstack', max_length=20)),
                ('tags', models.CharField(help_text='Comma separated, e.g. React, Node.js', max_length=200)),
                ('live_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('glyph', models.CharField(default='{ }', help_text='Symbol shown on card', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
