# Generated by Django 6.1 on 2026-08-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='twitter',
        ),
    ]
